//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domasna3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mapa
    {
        public long id { get; set; }
        public string city { get; set; }
        public string name { get; set; }
        public string street { get; set; }
        public double lat { get; set; }
        public double lon { get; set; }
    }
}
